name: CI - React Build e Test

on:
  pull_request:
    branches:
      - develop
      - main

env:
  NODE_VERSION: "24.14.0"
  IMAGE_NAME: brunomarch/build-react

jobs:
  build:
    name: Build e Test
    runs-on: [self-hosted, Linux, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

  docker-build:
    name: Docker Build (validação)
    runs-on: [self-hosted, Linux, build]
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build da imagem (sem push)
        uses: ./.github/actions/docker-build-push
        with:
          image-name: "${{ env.IMAGE_NAME }}"
          image-tag: "${{ github.sha }}"
          push: "false"
